services:
  postgres:
    image: postgres:15
    container_name: jumptotech-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: jumptotech
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  auth-service:
    build: ./services/auth-service
    ports:
      - "8001:8000"

  courses-service:
    build: ./services/courses-service
    ports:
      - "8002:8000"
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASS: admin123
      DB_NAME: jumptotech
    depends_on:
      - postgres

  enrollment-service:
    build: ./services/enrollment-service
    ports:
      - "8003:8000"

  content-service:
    build: ./services/content-service
    ports:
      - "8004:8000"

  news-service:
    build: ./services/news-service
    ports:
      - "8005:8000"

  gateway-service:
    build: ./services/gateway-service
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - courses-service
      - enrollment-service
      - content-service
      - news-service

volumes:
  postgres-data: